### ISSUE TITLE
Cannot get ContentState in CompositeDecorator

### ISSUE THREAD

**Issue by kurisLei** [SamyPesse/draftjs-multidecorators#4]
Hello, I am honored to use your open source works, but I encountered a problem, please help me!
Problem Description: I need to get EntityType from contentState, but I cannot get.
![image](https://user-images.githubusercontent.com/37492353/77253677-b5403680-6c96-11ea-91cc-5d6712210775.png)

![image](https://user-images.githubusercontent.com/37492353/77253615-537fcc80-6c96-11ea-80d5-70d845b0ad31.png)

**Comment by brik-dm** [comment]
Hi @kurisLei how dod you resolve this issue?

**Comment by kurisLei** [comment]
@spacedust 
你需要对这个依赖包的index文件做如下修改：
![iShot2020-03-24上午01 34 14](https://user-images.githubusercontent.com/37492353/77345450-982b6680-6d6f-11ea-87ac-a616295042b3.png)
